/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`bibles` /*!40100 DEFAULT CHARACTER SET latin7 */;

USE `bibles`;

/*Table structure for table `key_abbreviations_english` */

DROP TABLE IF EXISTS `key_abbreviations_english`;

CREATE TABLE `key_abbreviations_english` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Abbreviation ID',
  `a` varchar(255) NOT NULL,
  `b` smallint(5) unsigned NOT NULL COMMENT 'ID of book that is abbreviated',
  `p` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether an abbreviation is the primary one for the book',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=430 DEFAULT CHARSET=latin1 COMMENT='A table mapping book abbreviations to the book they refer to';

/*Data for the table `key_abbreviations_english` */

LOCK TABLES `key_abbreviations_english` WRITE;

insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (1,'Gen',1,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (2,'Ge',1,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (3,'Gn',1,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (4,'Exo',2,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (5,'Ex',2,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (6,'Exod',2,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (7,'Lev',3,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (8,'Le',3,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (9,'Lv',3,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (10,'Num',4,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (11,'Nu',4,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (12,'Nm',4,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (13,'Nb',4,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (14,'Deut',5,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (15,'Dt',5,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (16,'Josh',6,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (17,'Jos',6,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (18,'Jsh',6,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (19,'Judg',7,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (20,'Jdg',7,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (21,'Jg',7,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (22,'Jdgs',7,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (23,'Rth',8,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (24,'Ru',8,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (25,'1 Sam',9,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (26,'1 Sa',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (27,'1Samuel',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (28,'1S',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (29,'I Sa',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (30,'1 Sm',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (31,'1Sa',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (32,'I Sam',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (33,'1Sam',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (34,'I Samuel',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (35,'1st Samuel',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (36,'First Samuel',9,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (37,'2 Sam',10,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (38,'2 Sa',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (39,'2S',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (40,'II Sa',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (41,'2 Sm',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (42,'2Sa',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (43,'II Sam',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (44,'2Sam',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (45,'II Samuel',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (46,'2Samuel',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (47,'2nd Samuel',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (48,'Second Samuel',10,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (49,'1 Kgs',11,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (50,'1 Ki',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (51,'1K',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (52,'I Kgs',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (53,'1Kgs',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (54,'I Ki',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (55,'1Ki',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (56,'I Kings',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (57,'1Kings',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (58,'1st Kgs',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (59,'1st Kings',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (60,'First Kings',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (61,'First Kgs',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (62,'1Kin',11,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (63,'2 Kgs',12,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (64,'2 Ki',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (65,'2K',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (66,'II Kgs',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (67,'2Kgs',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (68,'II Ki',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (69,'2Ki',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (70,'II Kings',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (71,'2Kings',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (72,'2nd Kgs',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (73,'2nd Kings',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (74,'Second Kings',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (75,'Second Kgs',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (76,'2Kin',12,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (77,'1 Chron',13,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (78,'1 Ch',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (79,'I Ch',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (80,'1Ch',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (81,'1 Chr',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (82,'I Chr',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (83,'1Chr',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (84,'I Chron',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (85,'1Chron',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (86,'I Chronicles',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (87,'1Chronicles',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (88,'1st Chronicles',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (89,'First Chronicles',13,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (90,'2 Chron',14,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (91,'2 Ch',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (92,'II Ch',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (93,'2Ch',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (94,'II Chr',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (95,'2Chr',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (96,'II Chron',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (97,'2Chron',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (98,'II Chronicles',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (99,'2Chronicles',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (100,'2nd Chronicles',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (101,'Second Chronicles',14,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (102,'Ezra',15,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (103,'Ezr',15,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (104,'Neh',16,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (105,'Ne',16,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (106,'Esth',19,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (107,'Es',19,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (108,'Job',20,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (109,'Job',20,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (110,'Jb',20,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (111,'Pslm',21,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (112,'Ps',21,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (113,'Psalms',21,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (114,'Psa',21,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (115,'Psm',21,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (116,'Pss',21,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (117,'Prov',22,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (118,'Pr',22,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (119,'Prv',22,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (120,'Eccles',23,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (121,'Ec',23,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (122,'Qoh',23,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (123,'Qoheleth',23,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (124,'Song',24,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (125,'So',24,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (126,'Canticle of Canticles',24,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (127,'Canticles',24,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (128,'Song of Songs',24,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (129,'SOS',24,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (130,'Isa',27,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (131,'Is',27,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (132,'Jer',28,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (133,'Je',28,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (134,'Jr',28,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (135,'Lam',29,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (136,'La',29,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (137,'Ezek',31,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (138,'Eze',31,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (139,'Ezk',31,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (140,'Dan',32,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (141,'Da',32,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (142,'Dn',32,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (143,'Hos',33,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (144,'Ho',33,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (145,'Joel',34,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (146,'Joe',34,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (147,'Jl',34,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (148,'Amos',35,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (149,'Am',35,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (150,'Obad',36,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (151,'Ob',36,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (152,'Jnh',37,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (153,'Jon',37,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (154,'Micah',38,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (155,'Mic',38,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (156,'Nah',39,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (157,'Na',39,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (158,'Hab',40,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (159,'Zeph',41,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (160,'Zep',41,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (161,'Zp',41,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (162,'Haggai',42,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (163,'Hag',42,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (164,'Hg',42,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (165,'Zech',43,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (166,'Zec',43,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (167,'Zc',43,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (168,'Mal',44,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (169,'Mal',44,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (170,'Ml',44,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (171,'Matt',47,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (172,'Mt',47,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (173,'Mrk',48,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (174,'Mk',48,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (175,'Mr',48,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (176,'Luk',49,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (177,'Lk',49,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (178,'John',50,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (179,'Jn',50,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (180,'Jhn',50,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (181,'Acts',51,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (182,'Ac',51,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (183,'Rom',52,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (184,'Ro',52,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (185,'Rm',52,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (186,'1 Cor',53,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (187,'1 Co',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (188,'I Co',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (189,'1Co',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (190,'I Cor',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (191,'1Cor',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (192,'I Corinthians',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (193,'1Corinthians',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (194,'1st Corinthians',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (195,'First Corinthians',53,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (196,'2 Cor',54,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (197,'2 Co',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (198,'II Co',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (199,'2Co',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (200,'II Cor',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (201,'2Cor',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (202,'II Corinthians',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (203,'2Corinthians',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (204,'2nd Corinthians',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (205,'Second Corinthians',54,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (206,'Gal',55,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (207,'Ga',55,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (208,'Ephes',56,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (209,'Eph',56,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (210,'Phil',57,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (211,'Php',57,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (212,'Col',58,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (213,'Col',58,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (214,'1 Thess',59,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (215,'1 Th',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (216,'I Th',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (217,'1Th',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (218,'I Thes',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (219,'1Thes',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (220,'I Thess',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (221,'1Thess',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (222,'I Thessalonians',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (223,'1Thessalonians',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (224,'1st Thessalonians',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (225,'First Thessalonians',59,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (226,'2 Thess',60,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (227,'2 Th',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (228,'II Th',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (229,'2Th',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (230,'II Thes',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (231,'2Thes',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (232,'II Thess',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (233,'2Thess',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (234,'II Thessalonians',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (235,'2Thessalonians',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (236,'2nd Thessalonians',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (237,'Second Thessalonians',60,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (238,'1 Tim',61,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (239,'1 Ti',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (240,'I Ti',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (241,'1Ti',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (242,'I Tim',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (243,'1Tim',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (244,'I Timothy',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (245,'1Timothy',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (246,'1st Timothy',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (247,'First Timothy',61,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (248,'2 Tim',62,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (249,'2 Ti',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (250,'II Ti',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (251,'2Ti',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (252,'II Tim',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (253,'2Tim',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (254,'II Timothy',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (255,'2Timothy',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (256,'2nd Timothy',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (257,'Second Timothy',62,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (258,'Titus',63,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (259,'Tit',63,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (260,'Philem',64,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (261,'Phm',64,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (262,'Hebrews',65,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (263,'Heb',65,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (264,'James',66,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (265,'Jas',66,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (266,'Jm',66,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (267,'1 Pet',67,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (268,'1 Pe',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (269,'I Pe',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (270,'1Pe',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (271,'I Pet',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (272,'1Pet',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (273,'I Pt',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (274,'1 Pt',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (275,'1Pt',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (276,'I Peter',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (277,'1Peter',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (278,'1st Peter',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (279,'First Peter',67,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (280,'2 Pet',68,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (281,'2 Pe',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (282,'II Pe',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (283,'2Pe',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (284,'II Pet',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (285,'2Pet',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (286,'II Pt',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (287,'2 Pt',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (288,'2Pt',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (289,'II Peter',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (290,'2Peter',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (291,'2nd Peter',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (292,'Second Peter',68,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (293,'1 John',69,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (294,'1 Jn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (295,'I Jn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (296,'1Jn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (297,'I Jo',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (298,'1Jo',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (299,'I Joh',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (300,'1Joh',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (301,'I Jhn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (302,'1 Jhn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (303,'1Jhn',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (304,'I John',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (305,'1John',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (306,'1st John',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (307,'First John',69,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (308,'2 John',70,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (309,'2 Jn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (310,'II Jn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (311,'2Jn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (312,'II Jo',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (313,'2Jo',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (314,'II Joh',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (315,'2Joh',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (316,'II Jhn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (317,'2 Jhn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (318,'2Jhn',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (319,'II John',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (320,'2John',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (321,'2nd John',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (322,'Second John',70,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (323,'3 John',71,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (324,'3 Jn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (325,'III Jn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (326,'3Jn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (327,'III Jo',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (328,'3Jo',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (329,'III Joh',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (330,'3Joh',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (331,'III Jhn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (332,'3 Jhn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (333,'3Jhn',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (334,'III John',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (335,'3John',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (336,'3rd John',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (337,'Third John',71,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (338,'Jude',72,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (339,'Jud',72,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (340,'Rev',73,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (341,'Re',73,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (342,'The Revelation',73,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (343,'Genesis',1,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (344,'Exodus',2,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (345,'Leviticus',3,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (346,'Numbers',4,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (347,'Deuteronomy',5,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (348,'Joshua',6,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (349,'Judges',7,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (350,'Ruth',8,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (351,'1 Samuel',9,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (352,'2 Samuel',10,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (353,'1 Kings',11,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (354,'2 Kings',12,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (355,'1 Chronicles',13,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (356,'2 Chronicles',14,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (357,'Ezra',15,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (358,'Nehemiah',16,2);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (359,'Esther',19,2);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (360,'Job',20,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (361,'Psalms',21,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (362,'Psalm',21,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (363,'Proverbs',22,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (364,'Ecclesiastes',23,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (365,'Song of Solomon',24,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (366,'Isaiah',27,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (367,'Jeremiah',28,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (368,'Lamentations',29,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (369,'Ezekiel',31,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (370,'Daniel',32,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (371,'Hosea',33,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (372,'Joel',34,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (373,'Amos',35,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (374,'Obadiah',36,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (375,'Jonah',37,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (376,'Micah',38,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (377,'Nahum',39,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (378,'Habakkuk',40,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (379,'Zephaniah',41,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (380,'Haggai',42,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (381,'Zechariah',43,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (382,'Malachi',44,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (383,'Matthew',47,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (384,'Mark',48,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (385,'Luke',49,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (386,'John',50,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (387,'Acts',51,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (388,'Romans',52,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (389,'1 Corinthians',53,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (390,'2 Corinthians',54,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (391,'Galatians',55,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (392,'Ephesians',56,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (393,'Philippians',57,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (394,'Colossians',58,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (395,'1 Thessalonians',59,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (396,'2 Thessalonians',60,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (397,'1 Timothy',61,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (398,'2 Timothy',62,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (399,'Titus',63,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (400,'Philemon',64,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (401,'Hebrews',65,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (402,'James',66,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (403,'1 Peter',67,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (404,'2 Peter',68,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (405,'1 John',69,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (406,'2 John',70,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (407,'3 John',71,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (408,'Jude',72,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (409,'Revelation',73,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (410,'Tobias',17,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (411,'Tob',17,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (412,'To',17,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (413,'Judith',18,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (414,'Jdt',18,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (415,'Wisdom',25,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (416,'Wis',25,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (417,'W',25,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (418,'Sirach',26,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (419,'Sir',26,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (420,'Baruch',30,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (421,'Bar',30,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (422,'1 Maccabees',45,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (423,'1 Mac',45,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (424,'I Mac',45,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (425,'I Macabees',45,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (426,'2 Maccabees',46,1);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (427,'2 Mac',46,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (428,'II Mac',46,0);
insert  into `key_abbreviations_english`(`id`,`a`,`b`,`p`) values (429,'II Macabees',46,0);

UNLOCK TABLES;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
